#!/usr/bin/env bash
# https://betterdev.blog/minimal-safe-bash-script-template/

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

# script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

usage() {
  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-f] [-b] [-d] [-x]

Setup your computer with all your dotfile junk.

Available options:

-h, --help      Print this help and exit
-v, --verbose   Print script debug info
-f, --fresh     Do everything (for setting up new machines)

-b, --bundle-homebrew      Install Homebrew apps and dependencies
-d, --link-dotfiles        Symlink dotfiles
-x, --install-devbox       Install Devbox
EOF
  exit
}

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

setup_colors() {
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
  else
    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
  fi
}

msg() {
  echo >&2 -e "${1-}"
}

die() {
  local msg=$1
  local code=${2-1} # default exit status 1
  msg "$msg"
  exit "$code"
}

  # default values of variables set from params
  bundle_homebrew=0
  install_devbox=0
  link_dotfiles=0

parse_params() {

  while :; do
    case "${1-}" in
    -h | --help) usage ;;
    -v | --verbose) set -x ;;
    --no-color) NO_COLOR=1 ;;
    -b | --bundle-homebrew)   bundle_homebrew=1 ;;
    -d | --link-dotfiles)     link_dotfiles=1 ;;
    -x | --install-devbox)    install_devbox=1 ;;
    -f | --fresh) 
      bundle_homebrew=1
      install_devbox=1
      link_dotfiles=1
      ;;
    # -p | --param) # example named parameter
    #   param="${2-}"
    #   shift
    #   ;;
    -?*) die "Unknown option: $1" ;;
    *) break ;;
    esac
    shift
  done

  args=("$@")

  # check required params and arguments
  # [[ -z "${param-}" ]] && die "Missing required parameter: param"
  # [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"

  return 0
}

info() {
  msg "${CYAN}$1${NOFORMAT}"
}

warn() {
  msg "${YELLOW}$1${NOFORMAT}"
}

success() {
  msg "${GREEN}$1${NOFORMAT}"
}

parse_params "$@"
setup_colors

DOTFILES="$HOME/.dotfiles"

info "Setting up your Mac..."

get_devbox() {
  info "Installing devbox..."

  # Check for Nix and install if we don't have it
  if test ! "$(which nix)"; then
    warn "Nix not installed, brazenly piping curl into our shell"
    /bin/bash -c "$(curl -L https://nixos.org/nix/install)"
  fi

  # Check for Debox and install if we don't have it
  if test ! "$(which devbox)"; then
    warn "Devbox not installed, brazenly piping curl into our shell"
    /bin/bash -c "$(curl -fsSL https://get.jetpack.io/devbox)"
  fi

  success "Devbox installed"
}

get_brewing() {
  info "Installing apps and dependencies from Homebrew..."
  warn "This is gonna be a while ☕️"

  # Check for Homebrew and install if we don't have it
  if test ! "$(which brew)"; then
    warn "Homebrew not installed, brazenly piping curl into our shell"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  brew update
  brew tap homebrew/bundle
  brew bundle --file "$DOTFILES/.config/brewfile/Brewfile"

  # Install fzf keybindings and completion
  info "Setting up fzf..."
  "$(brew --prefix)/opt/fzf/install" --key-bindings --completion --no-update-rc

  success "Homebrew apps and dependencies installed successfully 🍻"
}

setup_dotfiles() {
  info "Linking dotfiles..."

  # Removes .zshrc from $HOME (if it exists) and symlinks the .zshrc file from the .dotfiles
  rm -rf "$HOME/.zshrc"
  ln -s "$DOTFILES/.zshrc" "$HOME/.zshrc"

  # Symlink all the things
  ln -s "$DOTFILES/.config" "$HOME/.config"
  # ln -s "$DOTFILES/.mackup.cfg" "$HOME/.mackup.cfg" # not sure I want to use mackup... 
  ln -s "$DOTFILES/.config/git/config" "$HOME/.gitconfig"
  ln -s "$DOTFILES/.gitignore_global" "$HOME/.gitignore_global"

  success "Dotfiles all linked up"
}

# Execute setup steps based on flags
if [[ $bundle_homebrew -eq 1 ]]; then
  get_brewing
fi

if [[ $install_devbox -eq 1 ]]; then
  get_devbox
fi

if [[ $link_dotfiles -eq 1 ]]; then
  setup_dotfiles
fi

success "\nSetup complete! 🎉"
